# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'IOSSkillTest' do
   pod 'AFNetworking', '~> 2.0'
   pod 'SVProgressHUD'
end

